### ISSUE TITLE
No such file or directory: 'espeak-ng'

### ISSUE THREAD

**Issue by pythaya** [espeak-ng/espeak-ng#1721]
When I try to run the basic demo code:
`import os`
`from espeakng import ESpeakNG` 
`esng = ESpeakNG()` 
`esng.say('Hello World!')`
I get this error:
`Traceback (most recent call last):
  File "/home/virgile/PycharmProjects/pythonProject/test2.py", line 5, in <module>
    esng.say('Hello World!')
  File "/home/virgile/miniconda3/envs/pythonProject/lib/python3.10/site-packages/espeakng/__init__.py", line 103, in say
    return self._espeak_exe(args, sync=sync)
  File "/home/virgile/miniconda3/envs/pythonProject/lib/python3.10/site-packages/espeakng/__init__.py", line 66, in _espeak_exe
    p = subprocess.Popen(cmd,
  File "/home/virgile/miniconda3/envs/pythonProject/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/virgile/miniconda3/envs/pythonProject/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'espeak-ng'`
I don't understand exactly what the issue is. Any suggestion ? 
PS: Im am on Ubuntu 22.04.02 and I use Python3.10 with Pycharm.

**Comment by jaacoppi** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'espeak-ng'`

Looks like you're trying to invoke the command 'espeak-ng' but you don't have it installed, or at least not installed in your $PATH.
